server:
  port: 8080 
  servlet:
    context-path: /gutenberg


#baseBooksUrl: "http://localhost:8081"    
#baseOrdersUrl: "http://localhost:8083"  
#baseReviewsUrl: "http://localhost:8082"    
#baseUsersUrl: "http://localhost:8084"



baseBooksUrl: "http://localhost:5555/books"    
baseOrdersUrl: "http://localhost:5555/orders"  
baseReviewsUrl: "http://localhost:5555/reviews"    
baseUsersUrl: "http://localhost:5555/users"




# Logging pattern for the console
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
 
