server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native: 
          searchLocations: 
            # edit this line to match your own file system
            file:///home/dominique/gutenberg-rhapsody/config-repo
